version: "3.9"

services:
  database:
    platform: linux/x86_64
    image: mysql
    container_name: mysqlProducts
    ports:
      - "3307:3306"
    volumes:
      - ./:/app/
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - keycloak-net

  rabbitmq-container:
    image: rabbitmq:3.11-management
    hostname: rabbitmq-container
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - keycloak-net

  app:
    container_name: productService
    command: java -jar target/productService-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      database:
        condition: service_healthy
      rabbitmq-container:
        condition: service_started
    volumes:
      #- ./:/app/app
      - ./target/productService-0.0.1-SNAPSHOT.jar:/app/productService-0.0.1-SNAPSHOT.jar


    networks:
      - keycloak-net
    environment:
        - spring_datasource_url=jdbc:mysql://mysqlProducts:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        - spring_rabbitmq_host=rabbitmq-container
        - spring_rabbitmq_port=5672
        #- SPRING_PROFILES_ACTIVE=prod


networks:
  keycloak-net:
    name: keycloak-net
